let Strings = {
  permission_text: {
    permission_decline: 'User declined messaging permissions :(',
    allow_text: 'Please Allow to procced further',
    not_allow: "Don't Allow",
    allow: 'Allow',
    logout_text: 'Are you sure you want to logout?',
    yes_text: 'Yes',
    no_text: 'No',
    exit_txt: 'Are you sure you want to exit the application?',
  },
  alert: {
    pass_reset:
      'Your password has been successfully reset Click below to sign in magically.',
    alert_text: 'Alert',
  },

  auth: {
    welcome: 'Welcome !',
    continue: 'Sign in to Continue',
    no_account: 'Don’t have an account yet?',
    sign_up: 'Sign Up',
    sign_in: 'Sign In',
    keep_in: 'Keep me signed in',
    forget: 'Forget  Password ?',
    set_pass: 'Set New Password',
    auth: 'Two factor authentication ',
    code_sent: 'Verification Code Sent on',
    continue: 'Continue',
    cancel: 'Cancel',
    reset: 'Reset password',
    not_receive: 'Did not receive code?',
    resend: 'Resend Code',
    already_acount: 'Already have an account?',
    signUp_heading: 'Enter your details for creating account. Thanks',
    personal_details: 'Personal Details',
    add_emergnecy: 'Add Emergency Contact',
    save: 'Save & Next',
    profile: 'Profile Creation',
  },
  form: {
    phone: 'Phone Number',
    mobile: 'Mobile Number',
    pass: 'Password',
    email: 'Email Address',
    confirm: 'Confirm Password',
    fname: 'Full Name',
    gender: 'Gender',
    dob: 'Date of Birth',
    blood_grp: 'Blood Group',
    martial: 'Marital Status',
    m_name: 'Middle Name',
    l_name: 'Last Name',
    age: 'Age',
    address: 'Address',
    neighbor: 'Neighborhood',
    country: 'Country',
    Region: 'Region',
    Province: 'Province',
    Department: 'Department',
    City: 'City',
    Village: 'Village',
    Pincode: 'Pincode',
    name: 'Name',
    relationship: 'Relationship',
  },
  validation: {
    diff_pass:
      'Your new password must be different to previously used passwords.',
    enter_code: 'Enter 4 digit code',
  },
};
module.exports = Strings;
