export const en = {
    common: {
        loading: 'Loading',
        connectionError: 'Connection error',
        save: 'Save',
        apiFetchError: 'something went wrong',
        tryAgain: 'Try Again',
    },
    home: {
        header: 'Home',
        message: 'Welcome',
        variant: 'App variant: ',
        emptyMessage:
            'Adding stories from the native app is coming soon. In the mean time head over to the web and add your first story.',
        share: 'Share',
        comment: 'Comment',
    },

    login: {
        username: 'Username',
        usernameHint: 'Enter your username',
        signIn: 'Sign in',
        password: 'Password',
        passwordHint: 'Enter your password',
        invalidCredentials: 'Invalid Username/Password',
        account: "Don't have an account?",
        signup: 'Sign up',
        googleBtn: 'Continue with Google',
        signinError: 'Login Error',
        signUpForFree: 'Sign up for free',
        nextChapter: 'The next chapter in family history.',
        explore: 'Explore your heritage, curate family moments, and share the magic of stories.',
        alreadyHaveAccount: 'Already have an account?',
        forgotPassword: 'Forgot Password?',
        fbLogin: 'Sign in with facebook',
    },
    signUp: {
        title: 'Title',
        firstName: 'First Name',
        lastName: 'Last Name',
        gender: 'Gender',
        email: 'Email',
        dateOfBirth: 'Date of Birth',
        phone: 'Phone Number',
        picture: 'Profile Photo',
        location: 'Location',
    },
    validation: {
        require: 'Field is required',
        invalid_email: 'Please enter valid mail',
    },
};
