export const en = {
    common: {
        loading: 'Loading',
        connectionError: 'Connection error',
        save: 'Save',
        apiFetchError: 'something went wrong',
        tryAgain: 'Try Again',
    },
    home: {
        header: 'Home',
        message: 'Welcome',
        variant: 'App variant: ',
        emptyMessage:
            'Adding stories from the native app is coming soon. In the mean time head over to the web and add your first story.',
        share: 'Share',
        comment: 'Comment',
    },

    login: {
        username: 'Username',
        usernameHint: 'Enter your username',
        signIn: 'Sign in',
        password: 'Password',
        passwordHint: 'Enter your password',
        invalidCredentials: 'Invalid Username/Password',
        account: "Don't have an account?",
        signup: 'Sign up',
        googleBtn: 'Continue with Google',
        signinError: 'Login Error',
        signUpForFree: 'Sign up for free',
        nextChapter: 'The next chapter in family history.',
        explore: 'Explore your heritage, curate family moments, and share the magic of stories.',
        alreadyHaveAccount: 'Already have an account?',
        forgotPassword: 'Forgot Password?',
        fbLogin: 'Sign in with facebook',
    },

    editProfile: {
        title: 'Edit Profile',
        fname: 'First Name(s)',
        lname: 'Last Name(s)',
        email: 'Email',
        resizePhoto: 'Resize Profile Photo',
        chooseNew: 'Select New Profile Photo',
        removeProfilePhoto: 'Remove Profile Photo',
        selectProfilePhoto: 'Select a Photo',
        profileUpdate: 'Profile details updated',
    },

    editPerson: {
        alertTitle: 'Are you sure?',
        alertText: 'Do you want to close this person? You’ll lose any edits you’ve made.',
        alertLeftText: 'Continue editing',
        alertRightText: 'Close',
        personIsliving: 'This person is living',
        placeSuggestion: 'City, County, State, Country',
        deathPlaceholder: 'Death Date or Year',
        birthPlaceholder: 'Birth Date or Year',
        other: 'Other',
        male: 'Male',
        female: 'Female',
        gender: 'Gender',
        firstNamePlaceholder: 'First & Middle Name(s)',
        header: 'Edit Person',
        deathplace: 'Death Place',
        birthplace: 'Birthplace',
        resizePhoto: 'Resize photo',
        chooseNew: 'Choose new photo',
        removePhoto: 'Remove photo',
        uploadPhoto: 'Upload Photo',
        takePhoto: 'Take a photo',
        friend: 'Friend',
        classmate: 'Classmate',
        neighbor: 'Neighbor',
        militaryComrade: 'Military Comrade',
        colleague: 'Colleague',
        fellowCongregant: 'Fellow Congregant',
        pet: 'Pet',
        whoIsConnected: 'Who is this person connected to?',
        whatIsRelation: 'What is their relationship?',
        selectRelation: 'Select relationship',
    },
};
