name: Pull Request into Master, Main, Develop and Preprod

on:
    push:
        branches:
            - 'master'
            - 'develop'
            - 'preprod'
            - 'main'
            - 'priya_dev'

jobs:
    #First job
    install-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'yarn'

            - name: Install Node modules
              uses: yarn ci

            - name: Linting
              run: yarn lint
    # # Second Job
    # build-android:
    #     needs: install-and-test
    #     uses: ./.github/workflows/build-android.yml
    #     secrets: inherit
