name: Pull Request into Master, Main, Develop, and Preprod

on:
    #pull_request:
    push:
        branches:
            - 'main'

jobs:
    install-and-test:
        runs-on: ubuntu-latest
        permissions: read-all
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: SonarCloud Scann
              uses: sonarsource/sonarcloud-github-action@master
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
              with:
                  args: >
                      -Dsonar.organisation=priyak-sdei
                      -Dsonar.projectKey=RN_NEW_ARCHITECTURE

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'yarn'

            - name: Install Node modules
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: yarn ci

            - name: Linting
              run: yarn lint

    # Second Job
    # build-android:
    #     needs: install-and-test
    #     uses: ./.github/workflows/build-android.yml
    #     secrets: inherit
