name: Pull Request into Master, Main, Develop, and Preprod

on:
    #pull_request:
    push:
        branches:
            - 'master'
            - 'develop'
            - 'preprod'
            - 'main'
            - 'priya_dev'

jobs:
    install-and-test:
        runs-on: ubuntu-latest
        permissions: read-all
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: SonarQube Scan
              uses: sonarsource/sonarqube-scan-action@master
              # with:
              #     sonarLogin: ${{ secrets.SONAR_TOKEN }}
              #     sonarProjectKey: 'smartData'
              #     sonarOrganization: 'smartData'
              #     sonarHostUrl: 'http://localhost:9000'
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  SONAR_HOST_URL: 'http://localhost:9000'

            - name: SonarQube Status
              uses: sonarsource/sonarqube-quality-gate-action@master
              timeout-minutes: 5
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'yarn'

            - name: Install Node modules
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: yarn ci

            - name: Linting
              run: yarn lint

    # Second Job
    # build-android:
    #     needs: install-and-test
    #     uses: ./.github/workflows/build-android.yml
    #     secrets: inherit
